# The URL the site will be built for
base_url = "https://www.oxidt.com"

title = "Oxidt"

theme = "duckquill"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [
  {name = "tags", feed = true},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# stylesheets = [
#   "style.css"
# ]

# Put all your custom variables here
primary_color = "#ff7800"
primary_color_alpha = "rgba(255, 120, 0, 0.2)"

# URL to issue tracker
issues_url = "https://github.com/hauju/blog/issues"

date_format = "%d %B %Y"

[extra.nav]
# Display Atom/RSS feed button in the nav
show_feed = false
# Whether to use icons in the nav
icons = true
# Links used in the nav; any icon from https://icons.getbootstrap.com
# can be used as the icon. The bi- prefix should not be added.
links = [
  {url = "/blog", name = "Blog", icon = "journal-bookmark"},
  {url = "https://github.com/hauju", name = "Github", icon = "code-slash"},
]

[extra.footer]
# "© Title, YEAR" in the footer
show_copyright = true
links = [
  {url = "/legal-notice", name = "Legal Notice", icon = "paragraph"},
  {url = "/privacy-policy", name = "Privacy Policy", icon = "shield"},
]
icons = true